#!/bin/bash
# git-commit-msg-linter@5.0.4 30/05/2023 16:15:15
# id=commit-msg-linter - THE id COMMENT SHOULD NOT BE DELETED OR MODIFIED!
# It's used to check whether this commit-msg hook file is created by us,
# if it is then we can remove it confidently on uninstallation.

.git/hooks/commit-msg $1
